fetch:
  url: https://www.arso.gov.si/xml/zrak/ones_zrak_urni_podatki_7dni.xml

preprocess:
  station: {}

train:
  station: "E410"
  test_size: 168
  window_size: 24
  target_col: "PM10"
  random_state: 42
